#!/bin/sh

case "$1" in
    start)
        # create DNS soft link
        ln -sf /run/NetworkManager/resolv.conf /etc/resolv.conf
        # show power on wellcome screen
        ;;
    stop)
        # Turn off BASE board
        stty -F /dev/ttyS1 1152000
        echo s > /dev/ttyS1
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
