#!/bin/sh

case "$1" in
    start)
        # create DNS soft link
        ln -sf /run/NetworkManager/resolv.conf /etc/resolv.conf
        # show power on wellcome screen
        ;;
    stop)
        # show power off goodbye screen
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
